# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: merlijnv/payloads
          tag_with_ref: true
      - name: Extract db
      # You may pin to the exact commit or the version.
      # uses: shrink/actions-docker-extract@7d86f1b9adc7afe4a64e13fb425872a547d6afa3
        uses: shrink/actions-docker-extract@v1
        with:
          # Docker Image to extract files from
          image: merlijnv/payloads
          # Path (from root) to a file or directory within Image
          path: /root/test.txt
